/**
 * SEO MANAGER — Dynamic Meta Tag Injection for SPA
 * Updates title, description, and Open Graph tags on route change.
 */

window.SeoManager = {
  defaultTitle: "Naroa Gutiérrez Gil | Artista Visual",
  defaultDescription: "Hiperrealismo POP. Retratos, murales y obra gráfica desde Bilbao.",
  defaultImage: "https://naroa.online/images/artworks/espejos-del-alma.webp",
  siteUrl: "https://naroa.online",

  init() {
    this.updateTags();
    window.addEventListener('hashchange', () => this.updateTags());
  },

  updateTags() {
    const hash = window.location.hash || '#/';
    
    // Clear previous artwork JSON-LD if exists
    this.clearArtworkJsonLd();

    if (hash.startsWith('#/obra/')) {
      const artworkId = hash.replace('#/obra/', '');
      this.setArtworkMeta(artworkId);
    } else if (hash.startsWith('#/galeria')) {
      this.setMeta(
        "Galería | Naroa Gutiérrez Gil",
        "Explora la colección completa de más de 40 obras de arte hiperrealista, pop art y mixed media.",
        "https://naroa.online/images/artworks/amy-rocks.webp"
      );
    } else if (hash.startsWith('#/juegos')) {
      this.setMeta(
        "Sala de Juegos | Naroa Gutiérrez Gil",
        "21 minijuegos interactivos basados en la obra de Naroa. Juega al Tetris, Snake o Memory versión artística.",
        "https://naroa.online/images/games-preview.webp" // Placeholder
      );
    } else {
      // Home / Default
      this.setMeta(
        this.defaultTitle,
        this.defaultDescription,
        this.defaultImage
      );
    }
  },

  setMeta(title, description, image) {
    document.title = title;
    
    this.setMetaTag('description', description);
    this.setMetaTag('og:title', title);
    this.setMetaTag('og:description', description);
    this.setMetaTag('og:image', image);
    this.setMetaTag('og:url', window.location.href);
    this.setMetaTag('twitter:title', title);
    this.setMetaTag('twitter:description', description);
    this.setMetaTag('twitter:image', image);
  },

  setMetaTag(name, content) {
    // Try to find by name first
    let tag = document.querySelector(`meta[name="${name}"]`);
    
    // If not found, try property (for OG tags)
    if (!tag) {
      tag = document.querySelector(`meta[property="${name}"]`);
    }
    
    // Update existing or create new
    if (tag) {
      tag.setAttribute('content', content);
    } else {
      const newTag = document.createElement('meta');
      if (name.startsWith('og:')) {
        newTag.setAttribute('property', name);
      } else {
        newTag.setAttribute('name', name);
      }
      newTag.setAttribute('content', content);
      document.head.appendChild(newTag);
    }
  },

  async setArtworkMeta(artworkId) {
    try {
      // Fetch SEO metadata (generated by Kimi)
      // We assume this JSON is loaded or we fetch it
      if (!window.seoArtworks) {
        const response = await fetch('data/seo-artworks.json');
        window.seoArtworks = await response.json();
      }

      const artwork = window.seoArtworks.artworks.find(a => a.id === artworkId);
      
      if (artwork) {
        const title = `${artwork.title} | Naroa Gutiérrez Gil`;
        const desc = artwork.metaDescription || `Obra ${artwork.title}, técnica ${artwork.technique}, año ${artwork.year}.`;
        const img = `${this.siteUrl}/${artwork.image || 'images/placeholder.webp'}`;

        this.setMeta(title, desc, img);
        
        // Inject JSON-LD Schema
        if (artwork.schemaLD) {
          this.injectJsonLd(artwork.schemaLD);
        }
      }
    } catch (e) {
      Logger.warn('SEO Manager: Could not load artwork data', e);
      this.setMeta(this.defaultTitle, this.defaultDescription, this.defaultImage);
    }
  },

  injectJsonLd(schemaData) {
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.id = 'dynamic-json-ld';
    script.text = JSON.stringify(schemaData);
    document.head.appendChild(script);
  },

  clearArtworkJsonLd() {
    const existing = document.getElementById('dynamic-json-ld');
    if (existing) existing.remove();
  }
};

// Initialize on load
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => window.SeoManager.init());
} else {
  window.SeoManager.init();
}
